# Generated by Django 3.0.3 on 2020-02-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Adamantane Antivirals', 'Adamantane Antivirals'), ('Adrenal Cortical Steroids', 'Adrenal Cortical Steroids'), ('Adrenal Corticosteroid Inhibitors', 'Adrenal Corticosteroid Inhibitors'), ('Allergenics', 'Allergenics'), ('Amebicides', 'Amebicides'), ('Analgesics', 'Analgesics'), ('Barbiturates', 'Barbiturates'), ('Biologicals', 'Biologicals'), ('Bronchodilators', 'Bronchodilators'), ('Calcimimetics', 'Calcimimetics'), ('Calcitonin', 'Calcitonin'), ('Catecholamines', 'Catecholamines'), ('Cephalosporins', 'Cephalosporins'), ('Coagulation Modifiers', 'Coagulation Modifiers'), ('Decongestants', 'Decongestants'), ('Diarylquinolines', 'Diarylquinolines'), ('Diuretics', 'Diuretics'), ('Echinocandins', 'Echinocandins'), ('Estrogens', 'Estrogens'), ('Fibric Acid Derivatives', 'Fibric Acid Derivatives'), ('Gallstone Solubilizing Agents', 'Gallstone Solubilizing Agents'), ('Glucocorticoids', 'Glucocorticoids'), ('Glycylcyclines', 'Glycylcyclines'), ('Gonadotropins', 'Gonadotropins'), ('H2 Antagonists', 'H2 Antagonists'), ('Heparins', 'Heparins'), ('Illicit', 'Illicit'), ('Insulin', 'Insulin'), ('Interferons', 'Interferons'), ('Interleukins', 'Interleukins'), ('Iodinated Contrast Media', 'Iodinated Contrast Media'), ('Iron Products', 'Iron Products'), ('Ketolides', 'Ketolides'), ('Laxatives', 'Laxatives')], max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('genericName', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Anaesthesiology', 'Anaesthesiology'), ('Nephrology', 'Nephrology'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Surgery', 'Surgery'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Cardiology', 'Cardiology'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Radiology', 'Radiology'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Apparel', 'Apparel'), ('Neurology', 'Neurology'), ('Sterilization', 'Sterilization'), ('Laboratory', 'Laboratory'), ('Gynecology & Urology', 'Gynecology & Urology')], max_length=100, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
