# Generated by Django 3.0.3 on 2020-02-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Otology and Neurotology', 'Otology and Neurotology'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Nephrology', 'Nephrology'), ('Laboratory', 'Laboratory'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Apparel', 'Apparel'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Neurology', 'Neurology'), ('Sterilization', 'Sterilization'), ('Radiology', 'Radiology'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Anaesthesiology', 'Anaesthesiology'), ('Surgery', 'Surgery'), ('Cardiology', 'Cardiology')], max_length=100, null=True),
        ),
    ]
