# Generated by Django 3.0.3 on 2020-02-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200228_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Radiology', 'Radiology'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Surgery', 'Surgery'), ('Cardiology', 'Cardiology'), ('Sterilization', 'Sterilization'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Gynecology & Urology', 'Gynecology & Urology'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Laboratory', 'Laboratory'), ('Neurology', 'Neurology'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Nephrology', 'Nephrology'), ('Apparel', 'Apparel'), ('Anaesthesiology', 'Anaesthesiology')], max_length=100, null=True),
        ),
    ]
