# Generated by Django 3.0.3 on 2020-02-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200228_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Anaesthesiology', 'Anaesthesiology'), ('Otology and Neurotology', 'Otology and Neurotology'), ('Sterilization', 'Sterilization'), ('Nephrology', 'Nephrology'), ('General Medical Equipment and Supplies', 'General Medical Equipment and Supplies'), ('Cardiology', 'Cardiology'), ('Ophthalmology and Optometry', 'Ophthalmology and Optometry'), ('Surgery', 'Surgery'), ('Physical and Occupational Therapy', 'Physical and Occupational Therapy'), ('Neurology', 'Neurology'), ('Gynecology & Urology', 'Gynecology & Urology'), ('Apparel', 'Apparel'), ('Dental E0quipment and Supplies', 'Dental Equipment and Supplies'), ('Obstetrics and Maternity Care', 'Obstetrics and Maternity Care'), ('Radiology', 'Radiology')], max_length=100, null=True),
        ),
    ]
